### ISSUE TITLE
Feat: 스플래시 화면 구현, 온보딩 화면 연결

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#1]
##  📌 Overview
-   스플래시 화면을 구현합니다.

<br />

## ✔️ Todo
- [x] 스플래시 화면 구현
- [x] 2초 유지 코드 추가
- [x] 이름 추가
- [x] 온보딩 화면 연결
