### ISSUE TITLE
Feat: 프로필 닉네임 수정 화면 구현

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#13]
##  📌 Overview
- 프로필 닉네임 수정 화면을 구현합니다.

<br />

## ✔️ Todo
- [x] 프로필 닉네임 수정 화면 구현
  - [x] 프로필 이미지 클릭 시 프로필 이미지 수정 화면 연결
  - [x] 닉네임 텍스트 필드 구현
  - [x] 닉네임 수정 기능 구현
  - [x] 유효성 검사, 상태 레이블 구현
  - [x] UserDefaults 값 수정
- [ ] NavigationBar 하단 Border 설정하기
- [ ] 기존 유저 아닐 경우 예외 처리 - 온보딩 화면 연결
  - [x] 임시 로직만 연결 중!

<br />

### 닉네임을 수정하고 이전 화면으로 돌아왔을 때 메뉴 셀에 장바구니 개수가 생기는 오류

- 닉네임을 수정한 뒤에 이전 화면으로 돌아왔을 때 장바구니 메뉴가 아닌 다른 메뉴 셀에서 장바구니 개수가 출력되는 오류
- 설정 테이블 뷰의 메뉴 셀을 만들 때 cellForRowAt 내에서 메뉴 셀의 0번째에만 장바구니 개수가 노출될 수 있도록 다른 UI 구성 함수를 사용하는데, 해당 함수에서 장바구니 이미지와 개수를 초기화해주지 않아서 해당 오류 발생
- 해당 UI 구성 함수에서 장바구니 이미지와 장바구니 개수를 초기화하여 해결

<img width="350" alt="닉네임 수정 전" src="https://github.com/dev-junehee/meaning-out/assets/116873887/b6eb4af3-32c4-4adb-b4d8-b92809ac7db7">
<img width="350" alt="닉네임 수정 후" src="https://github.com/dev-junehee/meaning-out/assets/116873887/c7e75dd6-f4ce-4c7b-b8d4-c07b6f685565">

```swift
// 수정 전
func configureCellData(data: String) {
      menuTitle.text = data
      cartLabel.text = ""
 }

// 수정 후
func configureCellData(data: String) {
      menuTitle.text = data
      cartImage.image = nil
      cartCount.text = ""
      cartLabel.text = ""
 }
```
