### ISSUE TITLE
Feat: 메인 화면, 검색 기능 구현

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#17]
##  📌 Overview
- 메인 화면을 구현합니다.
- 메인 화면을 구현하면서 검색 기능을 연결합니다.

<br />

## ✔️ Todo
- [x] 메인 화면 UI 구성
  - [x] SearchBar
  - [x] TableView + TableView Cell(최근검색 & 전체삭제용/검색어 리스트용 2가지)
  - [x] EmptyView
- [x] 검색 기능 연결 (사용자 입력 검색어 + API 코드 연결해서 결과만 확인하기)
- [x] 검색 결과 페이지네이션
- [x] 전체 삭제 클릭 시 최근 검색어 전체 삭제
- [ ] X버튼 클릭 시 해당 키워드 삭제
- [x] 검색 키워드 클릭 시 검색 결과 화면 연결 (push)

<br />

## 🔗 References
- [[UITableView] 아무 데이터가 없을 때 나오는 화면, 엠티뷰(empty view) 만들기](https://mini-min-dev.tistory.com/115)
- [UIView - isHidden](https://developer.apple.com/documentation/uikit/uiview/1622585-ishidden)
