### ISSUE TITLE
Feat: 최근 검색어 단일 삭제 기능

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#35]
##  📌 Overview
-  검색 화면에서 최근 검색어의 단일 내역 삭제 기능을 구현합니다.

<br />

## ✔️ Todo
- [x] tableView Cell tag 처리
- [x] 삭제 기능 구현 (버튼 핸들러에 sender.tag 통해 해당 데이터 접근 후 삭제)
- [x] BaseTableViewCell, BaseCollectionViewCell 생성/적용

<br />

### 단일 검색 내역 삭제 시 해당 검색어가 아닌 첫 번째 검색어가 삭제되는 오류

tag 처리를 삭제 버튼을 담당하는 xmark가 아닌 셀 자체에 주고 있었기 때문에 삭제 버튼 핸들러 내에서 sender.tag를 확인하면 0으로만 찍히는 것이 보였고, xmark에 tag를 주는 것으로 변경하여 해결

![](https://github.com/dev-junehee/meaning-out/assets/116873887/2d3f1c06-dd1a-4b89-a8f8-a02a0b2b7391)

- 변경 전
```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    guard let cell = tableView.dequeueReusableCell(withIdentifier: SearchItemTableViewCell.id, for: indexPath) as? SearchItemTableViewCell else { return SearchItemTableViewCell() }
    
    cell.selectionStyle = .none
    cell.tag = indexPath.row
    cell.xmark.addTarget(self, action: #selector(removeSearchList(_:)), for: .touchUpInside)
    cell.configureCellData(data: searchList[indexPath.row])
    
    return cell
}
```

- 변경 후

```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    guard let cell = tableView.dequeueReusableCell(withIdentifier: SearchItemTableViewCell.id, for: indexPath) as? SearchItemTableViewCell else { return SearchItemTableViewCell() }
    
    cell.selectionStyle = .none
    cell.xmark.tag = indexPath.row
    cell.xmark.addTarget(self, action: #selector(removeSearchList(_:)), for: .touchUpInside)
    cell.configureCellData(data: searchList[indexPath.row])
    
    return cell
}
```

| 변경 전 | 변경 후 |
|:------:|:-------:|
| ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-07-08 at 00 37 35](https://github.com/dev-junehee/meaning-out/assets/116873887/239ad5ec-3aaf-46d4-8075-b1e8eb5d1c4b) | ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-07-08 at 00 57 43](https://github.com/dev-junehee/meaning-out/assets/116873887/a5e848d7-374a-44e8-aca9-79bfb8566953)  |
