### ISSUE TITLE
Refactor: Base 코드 적용, View-Controller 분리 작업

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#36]
##  📌 Overview
- 프로젝트 전체 씬에서 Base 코드를 적용합니다.
- View와 ViewController를 분리합니다.

<br />

## ✔️ Todo
- [x] Base 코드 구현
- [x] 온보딩 화면
- [x] 프로필/닉네임 초기 설정 화면
- [x] 검색 화면
- [x] 설정 화면
- [ ] ~~프로필/닉네임 수정 화면~~ → 재사용으로 수정하기 위해 다른 브랜치에서 별도 진행
