### ISSUE TITLE
Feat: 찜 탭 - 찜한 상품 카테고리 구분 기능 연결

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#43]
##  📌 Overview
- Realm의 Link, EmbeddedObject, LinkingObjects 등을 통해 찜 탭에서 카테고리를 구분할 수 있도록 합니다.

<br />

## ✔️ Todo
- [x] 구조체명 수정 (Search → Shopping 변경)
- [x] Shopping 구조체 category1 추가
- [x] Realm Model - LikeCategory 추가 (realm list 활용)
- [x] LikeCategory - DetailData 추가 (기존 찜 데이터)
- [x] 찜 탭 - 카테고리 테이블뷰 추가
- [x] 찜 탭 - 카테고리 추가 기능 연결
- [x] 찜 탭 - 카테고리 삭제 기능 연결
- [x] 상품 검색 결과 - 찜 버튼 클릭 시 카테고리 선택 & 선택한 카테고리 찜 상품 추가 기능 연결
- [x] 상품 검색 결과 - 찜 해제 기능 연결
- [x] 그 외 예외처리

<br />

## 🔗 References
- [[iOS - swift] 7. 테이블 뷰 (table view)](https://ios-development.tistory.com/25)
- [UITableViewCell - Apple Developer ](https://developer.apple.com/documentation/uikit/uitableviewcell)
- [[iOS - swift] UITableView의 편집모드 사용 방법](https://ios-development.tistory.com/1363)

<br />
