### ISSUE TITLE
Refactor: 프로필 닉네임 수정 화면 MVVM 패턴 적용

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#46]
##  📌 Overview
- 프로필 닉네임을 설정하는 화면에 MVVM 패턴을 적용합니다.

<br />

## ✔️ Todo
- [x] Observable 클래스 생성
- [x] 닉네임 유효성 검사 로직 분리
- [x] 닉네임 저장 버튼 클릭 핸들러 로직 분리

<br />

## 🔗 References

<br />
