### ISSUE TITLE
Feat: 프로필 이미지 닉네임 설정 화면 구현, 메인화면 연결

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#5]
##  📌 Overview
- 프로필 이미지와 닉네임을 설정하는 화면을 구현합니다.

<br />

## ✔️ Todo
- [x] 화면 초기 진입 시 프로필 이미지 랜덤 출력
- [x] 프로필 이미지 클릭 시 이미지 선택 화면 연결 (push)
- [x] 닉네임 입력 시 유효성 검사 실행
  - [x] 유효성 검사는 사용자 입력값이 달라질 때마다 실행
  - [x] 유효성 결과에 따른 메세지 출력
- [x] 완료 버튼 클릭 시 rootViewController 메인 화면으로 교체
  - [x] isUser 값에 따라서 SceneDelegate rootViewController 교체
- [x] 뒤로가기 버튼 클릭 시 온보딩 화면 연결

<br />

## 🔗 References
- [[iOS] CollectionView 선택한 아이템 UI 변경하기](https://superwony.tistory.com/158)
CollectionView에서 Cell 클릭했을 때, isSelect 여부에 따라 Cell UI바꿔주기
- [https://tono18.tistory.com/20](https://tono18.tistory.com/20) , [Apple Developer - viewWillAppear(_:)](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621510-viewwillappear)
화면 push 후 다시 pop 됐을 때 데이터 불러오기
