### ISSUE TITLE
Refactor: 상품 검색 - 정렬 관련 중복 로직 개선

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#50]
##  📌 Overview
- 상품 검색 화면에서 정렬과 관련된 중복 코드를 개선합니다. (열거형 활용)

<br />

## ✔️ Todo
- [x] 정렬 버튼 핸들러 1개 함수로 활용할 수 있도록 수정
- [x] ReuseableProtocol Extension 중복 코드 개선 (UIView 상속)
- [x] 찜 카테고리 생성 Alert TextField 함 수정
