### ISSUE TITLE
Design: 앱 리디자인

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#64]
##  📌 Overview
- 앱 디자인을 변경합니다.

## ✔️ Todo
- [x] 런치스크린 수정
- [x] 온보딩 화면 수정
- [x] 기본 폰트 변경
- [x] 컬러 리소스 변경
