### ISSUE TITLE
Feat: 설정 화면 구현

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/meaning-out#7]
##  📌 Overview
-  설정 화면을 구현합니다. 
(User 탈퇴 처리와 rootViewController 연결 확인을 위해 해당 화면을 먼저 구현)

<br />

## ✔️ Todo
- [x] 설정 화면 테이블 뷰 구현
  - [x] 테이블 뷰 셀 구현
  - [ ] ~~장바구니 목록 셀에 장바구니 상품 개수 출력~~ **→ UserDefaultsManager 처리 후 작업 예정**
  - [x] 탈퇴하기 클릭 시 Alert
  - [x] 확인/취소에 따른 핸들링
    - [x] 확인 클릭 - 유저 데이터 삭제, 온보딩 화면 연결
    - [x] 취소 클릭 - return
- [ ] ~~사용자 가입 날짜 데이터 저장~~ **→ UserDefaultsManager 처리 후 작업 예정**
  - [ ] ~~가입 시점의 날짜를 UserDefaults에 저장~~ **→ UserDefaultsManager 처리 후 작업 예정**
- [x] 프로필 뷰 영역 선택 시 프로필 수정 화면 연결

<br />

## 🔗 References
- [iOS 15 + NavigationBar, Tabbar 배경 구분선 투명해진건에 대하여](https://yeop96.tistory.com/entry/iOS-15-NavigationBar-Tabbar-%EB%B0%B0%EA%B2%BD-%EA%B5%AC%EB%B6%84%EC%84%A0-%ED%88%AC%EB%AA%85%ED%95%B4%EC%A7%84%EA%B1%B4%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC)
iOS 15 버전부터 TabBar, NavigationBar 구분선이 바뀌었다는 걸 이제야 알았다! 

- [UIStackView의 Distribution](https://velog.io/@hanseop95/UIStackView%EC%9D%98-Distribution)
코드 베이스에서 레이아웃을 잡을 때 스택 뷰를 종종 사용하는데 distribution 개념이 잘 안 잡혀있다가 이 그림을 보고 이해도가 높아진 거 같다.

- [[Swift] UIAlertController 와 UIAlertAction 을 사용한 프로젝트](https://medium.com/eunjios-dev-blog/swift-uialertcontroller-%EC%99%80-uialertaction-%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%9C-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-2-2-5941f664a124)
Alert 띄울 때 클로저에 대한 개념이 부족해서 핸들러 활용을 못 하고 있었는데 이 블로그에 나와있는 전체 코드를 보고 대략적인 감을 잡아 시도해볼 수 있게 되었다!

<br />

### Missing package product <package name>
- 스뮬레이터 빌드 시 패키지를 찾지 못하는 오류
- File > Packages > Reset Package Caches

![](https://github.com/dev-junehee/meaning-out/assets/116873887/6c173dca-ed3e-44cb-b3e4-026eed7f39bd)
